### ISSUE TITLE
Bucket created outside cloudformation stack

### ISSUE THREAD

**Issue by dam-coder** [MikeSouza/serverless-deployment-bucket#3]
The plugin creates the bucket outside the cloudformation stack.
When removing the project from AWS using `serverless remove --stage dev`, the bucket is left behind because only the stack and its contents are deleted.
Is it possible to create the bucket inside the cloudformation stack?

**Comment by coyoteecd** [comment]
It's a good idea to have the bucket created outside the cloudformation stack. I for one can see utility in keeping the bucket even when removing the stack, because the deployment bucket is a "history" of deployed stacks.

What is missing is a way to optionally delete the bucket after the stack gets removed.

**Comment by MikeSouza** [comment]
@JohnMeireles Sorry, it's taken me so long to see this.

Deletion of the serverless deployment bucket is not ideal. Creation and maintaining it outside of the current CloudFormation stack (aka the current serverless.yaml project) is ideal. Especially if you wish to use a single bucket for a multi-stack project (multiple Serverless projects).

@coyoteecd has the right idea.

**Comment by Graham42** [comment]
It looks like it's possible to create with CloudFormation but not delete when the stack is deleted using the DeletionPolicy Attribute
https://aws.amazon.com/premiumsupport/knowledge-center/delete-cf-stack-retain-resources/

For a bucket that is re-used the more common use case might be to have an option to delete the folder associated with `deploymentPrefix`

**Comment by MikeSouza** [comment]
> It looks like it's possible to create with CloudFormation but not delete when the stack is deleted using the DeletionPolicy Attribute
> https://aws.amazon.com/premiumsupport/knowledge-center/delete-cf-stack-retain-resources/

There are a few problems with what you suggest, but the biggest one is that there is no good way from a plugin to create the deployment bucket as a part of the Serverless project's CloudFormation stack. This is simply because Serverless itself checks to see if the deployment bucket exists before it even validates or packages up the CloudFormation stack it applies.

>For a bucket that is re-used the more common use case might be to have an option to delete the folder associated with `deploymentPrefix`

When you do a `sls remove`, it removes the objects from the deployment bucket:
```
$ sls remove
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
```

**Comment by MikeSouza** [comment]
@Graham42 
> It looks like it's possible to create with CloudFormation but not delete when the stack is deleted using the DeletionPolicy Attribute
> https://aws.amazon.com/premiumsupport/knowledge-center/delete-cf-stack-retain-resources/

There are a few problems with what you suggest, but the biggest one is that there is no good way from a plugin to create the deployment bucket as a part of the Serverless project's CloudFormation stack. This is simply because Serverless itself checks to see if the deployment bucket exists before it even validates or packages up the CloudFormation stack it applies.

>For a bucket that is re-used the more common use case might be to have an option to delete the folder associated with `deploymentPrefix`

When you do a `sls remove`, it removes the objects from the deployment bucket:
```
$ sls remove
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
```
